def inertialVersion = project.hasProperty("INERTIAL_EVENTS_VERSION") ?
    project.property("INERTIAL_EVENTS_VERSION") : "1.4.0"

def inertialRepo = project.hasProperty("INERTIAL_EVENTS_MAVEN_REPO") ?
    project.property("INERTIAL_EVENTS_MAVEN_REPO") : "https://repo.situm.es/artifactory/libs-release-local"

repositories {
    maven { url inertialRepo }
    google()
    mavenCentral()
}

dependencies {
    implementation "es.situm:inertial-events-detection:${inertialVersion}@aar"
}
